### PR TITLE
Update sample YMLs and some changes in on-prem rehydration documentation

### PR DESCRIPTION
**Pull request by orhanasan**
I have updated sample YMLs for on-prem rehydration to rollout active memory management feature for rehydration handler. I also removed some undesired empty spaces and new lines. Also, I fixed some of the numberings.

### CODE REVIEW

**Comment by george-edgedelta** [comment]
Hi @orhanasan 

If you look at the attached screenshot, the numbered steps do not display correctly. 

When we first worked on this document, Taylan and I tried to figure out how to continue the numbered steps; however, we were unable to find a solution. As a result, we had to "manually" number the steps and eliminate the space between the numbers and words, such as "5.Deploy the agent," as opposed to "5. Deploy the agent." 

I understand that the document may not look its best. If you have the bandwidth, you are more than welcome to test around another possible solution; however, given that we will soon move to another documentation platform and given my workload, I would recommend that we revert your changes and keep the document as it was. 

Screen Shot 2022-01-25 at 10 26 22 AM

**Comment by orhanasan** [comment]
Hi @george-edgedelta,

If that is the case, I will revert the numbering changes in the next commit.

**Comment by orhanasan** [comment]
@george-edgedelta, I have reverted them

**Comment by george-edgedelta** [comment]
Thanks, @orhanasan

**Pull request merged**
